server: { port: 8082 }
spring:
  datasource: { url: jdbc:h2:mem:billing;DB_CLOSE_DELAY=-1, driverClassName: org.h2.Driver, username: sa }
  jpa: { hibernate: { ddl-auto: update } }
  cloud:
    stream:
      defaultBinder: kafka
      bindings:
        paymentReceived-out-0: { destination: payment.received }
      kafka:
        binder: { brokers: localhost:9092 }
