server: { port: 8086 }
spring:
  datasource: { url: jdbc:h2:mem:analytics;DB_CLOSE_DELAY=-1, driverClassName: org.h2.Driver, username: sa }
  jpa: { hibernate: { ddl-auto: update } }
  cloud:
    stream:
      defaultBinder: kafka
      bindings:
        appointmentStatusChanged-in-0: { destination: appointment.status.changed, group: analytics }
      kafka:
        binder: { brokers: localhost:9092 }
